# baseURL = 'https://blog.wangsyi.men'
languageCode = 'zh-CN'
title = "Wangs' note"
theme = "hugo-ficurinia"
[menu]
# [[menu.main]]
#   name = 'Home'
#   pageRef = '/'
#   weight = 10
[[menu.main]]
  name = 'Dev'
  pageRef = '/skills'
  weight = 10
[[menu.main]]
  name = 'Tutorials'
  pageRef = '/tutorials'
  weight = 20
[[menu.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 30



[params]
    author = "Wangs"
    description = "Wangs' note"  # this will be added as metadata

    posts = "tutorials"  # content directory where to find home page posts; default searches in "posts" and "post"
    showPostsLink = false  # show or hide the link to the simple post list
    extraContentDirs = []  # other content directories to render similarly to the home page
    showcaseDir = "showcase"  # create a content directory that shows a special showcase section in the home page